apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-gumy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-gumy
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-gumy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-gumy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-gumy
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gqlu-tenant/nodejs-users/simple-nodejs-app-gumy@sha256:c1939b3d70f9455a1c22601b4d098bb74b1ac00a2d9bc23b9f3459ed9f1f8194
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
